[package]
name = "schnorr-musig2"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
bitcoin = "0.32.6"
k256 = "0.13.4"
lazy_static = "1.5.0"
rand = "0.9.1"
rand_core = "0.9.3"
thiserror = "2.0.12"
